# Seja o exercício:

In [1]:
import numpy as np

In [2]:
#Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
Z = np.array([1,2,3,4,5])
nz = 3

In [3]:
# Solução fornecida
# Author: Warren Weckesser
def Z0():
    Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
    Z0[::nz+1] = Z
    return Z0
print(Z0())


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [4]:
%%timeit
# Timing it
Z0()

2.09 µs ± 80.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Criar outras soluções

Crie outras soluções utilizando matrizes e indexação matricial para o problema acima. 
Compare o tempo de execução de todas as soluções

A solução fornecida já é uma das mais eficientes. A seguir outras soluções.

# Solução não-pythonica

Essa é a solução menos eficiente, usando loops do python que geralmente são mais lentos que outros métodos.

In [5]:
def Z1():
    Z1 = np.zeros(len(Z) + (len(Z)-1)*(nz))
    zerosin = 0
    iz1 = 0
    for i,_ in enumerate(Z1):
        if i == 0 or zerosin == nz:
            Z1[i] = Z[iz1]
            iz1 += 1
            zerosin = 0
        else:
            zerosin += 1
    return Z1
print(Z1())

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [6]:
%%timeit
# Timing it
Z1()

5.97 µs ± 338 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Solução alternativa usando numpy

Essa solução usa uma função do numpy que insere (não substitui) no primeiro argumento valores do terceiro argumento, seguindo indices fornecidos pelo segundo argumento

In [7]:
def Z2():
    Z2 = np.zeros((len(Z)-1)*(nz))
    Z2 = np.insert(Z2, [i*(nz) for i in range(0, len(Z))], Z) 
    return Z2
print(Z2())

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [8]:
%%timeit
# Timing it
Z2()

34.6 µs ± 1.39 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# Solução usando mascara com iterators

Esta solução é diferente e utiliza iterators do python

Inicialmente, os indices do vetor resultando que não terão valor 0 são calculados, e os índices possíveis do vetor resultante também são alocados.

Para criar a resposta, realiza-se uma operação checando se o índice atual é um índice com valor não zero, se sim, o proximo valor do iterator formado do vetor original da pergunta é adicionado a resposta, se não zero.

Obviamente uma solução desnecessariamente complciada mas interessante.

In [9]:
def Z3():
    notzero_idx = [i*(nz+1) for i in range(0,len(Z))]
    Z3idx = np.arange(0,len(Z) + (len(Z)-1)*(nz), 1)

    Ziter = iter(Z)

    Z3 = [next(Ziter) if i in notzero_idx else 0 for i in Z3idx]
    return Z3
print(Z3())

[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]


In [10]:
%%timeit
# Timing it
Z3()

14.3 µs ± 438 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Análise de tempo de execução

Soluções mais rápidas:<br>
1- Z0<br>
2- Z1<br>
3- Z3<br>
4- Z2<br>

A solução com slicing original, Z0, utiliza todo o poder da indexação matricial do python e é difícil de ser superada. Interessantemente, a solução não pythonica com loops for foi mais rapida que Z3 e Z2, provavelmente pela quantidade reduzida de alocações na memória. 

Outra coisa interessante foi que utilizar a função insert do numpy foi a pior solução (Z2), com a abordagem de mascara booleana com iteradores (Z3) superando-a.
