In [1]:
import numpy as np

In [2]:
# Modificando tamanhos para visualização
A = np.random.randint(0,10,(3,4))


In [3]:
B = np.random.randint(0,10,(4,3))


# Modificar o notebook para explicar como os 3 comandos abaixo funcionam

# Para explicar o que está acontecendo, irei explicar o que cada comando/operação realiza nos códigos, com justificativa quando necessário.

In [4]:
#How to get the diagonal of a dot product? (★★★)

# Author: Mathieu Blondel

# Slow version

# Comando original 
C = np.diag(np.dot(A, B)) 

dot = np.dot(A, B) # faz a multiplicação matricial de A e B
C = np.diag(dot) # extrai a diagonal de uma matriz
print("A: " + str(A))
print("B: " + str(B))
print("A dot B faz multiplicação matricial:\n" + str(dot))
print("np.diag extrai a diagonal da matriz:\n" + str(C))


A: [[1 8 5 7]
 [8 9 0 3]
 [9 4 0 8]]
B: [[1 8 8]
 [4 3 5]
 [3 2 5]
 [5 1 3]]
A dot B faz multiplicação matricial:
[[ 83  49  94]
 [ 59  94 118]
 [ 65  92 116]]
np.diag extrai a diagonal da matriz:
[ 83  94 116]


# O primeiro método é bem direto ao ponto. Uma das funções calcula a mutliplicação matricial e o segundo extrai a diagonal.

# Segundo método:

In [5]:
# Fast version
# Comando original
#%timeit np.sum(A * B.T, axis=1)

Bt = B.T
print("Transposta de B:\n" + str(Bt))
AB = A*Bt
print("Resultado da multiplicação element wise com BT:\n" + str(AB))
sumaxis1 = np.sum(AB, axis=1)
print("Soma no eixo 1\n" + str(sumaxis1))

Transposta de B:
[[1 4 3 5]
 [8 3 2 1]
 [8 5 5 3]]
Resultado da multiplicação element wise com BT:
[[ 1 32 15 35]
 [64 27  0  3]
 [72 20  0 24]]
Soma no eixo 1
[ 83  94 116]


# Explicação segundo método:

Devido a transposição de B, a soma no axis=1 (soma horizontal) de A*Bt equivale aos calculos realizados em A.dot(B) para i = j (diagonal), tornando o processo mais eficiente por não calcular todos as somas de produtos dos outros elementos, que seriam calculados em A.dot(B).

# Terceiro método 
Essa abordagem utiliza a einsten sum, utilizando uma notação matemática introduzida por Einsten, onde índices na variável implicam soma dessa variavel em valores variando no índice. Alguns experimentos explorando a einsten sum. 

In [6]:
# Faster version
#%timeit np.einsum("ij,ji->i", A, B)

print("A: " + str(A), end='\n\n')
print("einsum('ij', A) =\n" + str(np.einsum('ij', A)), end=' = A\n\n')
print("einsum('ji', A) =\n" + str(np.einsum('ji', A)), end=' = A.T\n\n')
print("einsum('ij->j', A) =\n" + str(np.einsum('ij->j', A)), end=' = np.sum(A, axis=0), soma de cada coluna de A\n\n')
print("einsum('ij->i', A) =\n" + str(np.einsum('ij->i', A)), end=' = np.sum(A, axis=1), soma de cada linha de A\n\n')
print("einsum('ji->i', A) =\n" + str(np.einsum('ji->i', A)), end=' = np.sum(A.T, axis=1) soma de cada linha da transposta de A\n\n')
print("einsum('ij, ji', A, B) =\n" + str(np.einsum('ij,ji', A, B)), end=' = np.sum(A*B.T)\n\n\n')

print("De posse dos resultados dos experimentos anteriores, verifica se que a einsum realizada realiza a mesma operação do método 2:\n")

print("einsum('ij,ji->i', A, B) =\n" + str(np.einsum("ij,ji->i", A, B)), end=' = np.sum(A * B.T, axis=1)\n\n')

A: [[1 8 5 7]
 [8 9 0 3]
 [9 4 0 8]]

einsum('ij', A) =
[[1 8 5 7]
 [8 9 0 3]
 [9 4 0 8]] = A

einsum('ji', A) =
[[1 8 9]
 [8 9 4]
 [5 0 0]
 [7 3 8]] = A.T

einsum('ij->j', A) =
[18 21  5 18] = np.sum(A, axis=0), soma de cada coluna de A

einsum('ij->i', A) =
[21 20 21] = np.sum(A, axis=1), soma de cada linha de A

einsum('ji->i', A) =
[18 21  5 18] = np.sum(A.T, axis=1) soma de cada linha da transposta de A

einsum('ij, ji', A, B) =
293 = np.sum(A*B.T)


De posse dos resultados dos experimentos anteriores, verifica se que a einsum realizada realiza a mesma operação do método 2:

einsum('ij,ji->i', A, B) =
[ 83  94 116] = np.sum(A * B.T, axis=1)

