In [2]:
import numpy as np

In [3]:
# Modificando tamanhos para visualização
A = np.random.randint(0,10,(3,4))


In [4]:
B = np.random.randint(0,10,(4,3))


# Modificar o notebook para explicar como os 3 comandos abaixo funcionam

In [16]:
#How to get the diagonal of a dot product? (★★★)

# Author: Mathieu Blondel

# Slow version

# Comando original 
#%timeit C = np.diag(np.dot(A, B)) 

dot = np.dot(A, B) # faz a multiplicação matricial de A e B
C = np.diag(dot) # extrai a diagonal de uma matriz
print("A: " + str(A))
print("B: " + str(B))
print("A dot B faz multiplicação matricial:\n" + str(dot))
print("np.diag extrai a diagonal da matriz:\n" + str(C))


A: [[1 4 3 2]
 [5 7 4 9]
 [7 9 2 0]]
B: [[3 7 2]
 [0 4 6]
 [6 4 9]
 [5 4 9]]
A dot B faz multiplicação matricial:
[[ 31  43  71]
 [ 84 115 169]
 [ 33  93  86]]
np.diag extrai a diagonal da matriz:
[ 31 115  86]


In [18]:
# Fast version
# Comando original
# %timeit np.sum(A * B.T, axis=1)

Bt = B.T
print("Transposta de B:\n" + str(Bt))
AB = A*Bt
print("A multiplicação element wise com BT:\n" + str(AB))
sumaxis1 = np.sum(AB, axis=1)
print("Soma no eixo 1\n" + str(sumaxis1))

print("\nDevido a transposição de B, A*Bt equivale a A.dot(B). \n\nEm outras palavras, a transposição de B torna uma multiplicação linha linha do produto element wise fica igual a uma multiplicação linha por coluna da multiplicação matricial.\n\n A soma no eixo 1 resulta no resultado para i = j em A*B")

Transposta de B:
[[3 0 6 5]
 [7 4 4 4]
 [2 6 9 9]]
A multiplicação element wise com BT:
[[ 3  0 18 10]
 [35 28 16 36]
 [14 54 18  0]]
Soma no eixo 1
[ 31 115  86]

Devido a transposição de B, A*Bt equivale a A.dot(B). 

Em outras palavras, a transposição de B torna uma multiplicação linha linha do produto element wise fica igual a uma multiplicação linha por coluna da multiplicação matricial.

 A soma no eixo 1 resulta no resultado para i = j em A*B


In [18]:
# Faster version
# TODO
%timeit np.einsum("ij,ji->i", A, B)

360 µs ± 56.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
