In [1]:
import numpy as np

In [16]:
A = np.random.randint(0, 10, (3,3))
B = np.random.randint(0, 10, (3,3))

print(A)
print(B)

[[3 5 8]
 [5 1 3]
 [2 4 9]]
[[9 1 4]
 [3 2 4]
 [2 4 3]]


In [21]:
# NP DOT = matrix multiplication
dot = A.dot(B)
matmul = np.matmul(A, B)
print(dot)
print(matmul)


[[58 45 56]
 [54 19 33]
 [48 46 51]]
[[58 45 56]
 [54 19 33]
 [48 46 51]]


In [18]:
# Times (element-wise) 
times = A * B
print(times)

[[27  5 32]
 [15  2 12]
 [ 4 16 27]]
